### ISSUE TITLE
Create a product 

### ISSUE THREAD

**Issue by wenjialu** [NYUdevops-products/products#14]
**As a** user  
**I need** the ability to create new products on the website 
**So that** I can let others see our newly released goods.

**Details & Assumptions:** 
* POST http://[our domain]/products
* Json:
```
{
"id": "xxxxx",
"name": "iPhone",
"category": "phone",
"amount": "3",
"status": "PdtStatus.Normal",
}

```
**Acceptance Criteria:**
```gherkin
Given there is no expected product on the database yet
When the user submits the create product request,
Then it would return the json I have defined.
```

**Comment by zihaowang0916** [comment]
Under criteria, I added the "Given" situation

**Comment by zihaowang0916** [comment]
@wenjialu @BillChen666 @iswhr @mt4456 I suggest to correct status from status code to enumeration type (status_bad, status_good, status_great). For example, the status for a product "apple" is "status_good".
