### ISSUE TITLE
Create a README.md file

### ISSUE THREAD

**Issue by zihaowang0916** [NYUdevops-products/products#18]
**As a** [Developer ]  
**I need** [README.md] 
**So that** [Everyone can read it as instructions] 

**Details & Assumptions:** 
* give instructions on 
* 1. what calls are available 
* 2. what inputs they expect
* 3. how to run and test your code so that users will know how it works.

**Acceptance Criteria:**

```gherkin
Given [a new programmer gets the repository]
When [read this README.md file]
Then [the programmer can fully understand all the codes]
```

**Comment by wenjialu** [comment]
The "how to use" instruction should be written.
